# Quickstart
Importation de Tensorflow avec comme alias tf

In [2]:
import tensorflow as tf

Récupérer le dataset et convertir les nombres sous le format float

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

Mise en place du model par empilement de couche avec `tf.keras.Sequential`

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.80196935, -0.25085074, -0.23852324, -0.20314524, -0.35097277,
        -0.7058587 ,  0.3078978 , -0.23114908, -0.3885523 , -0.35823363]],
      dtype=float32)

La fonction `tf.nn.softmax` convertit les logits en probalités pour chaque classe


In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.05932322, 0.10293721, 0.10421403, 0.10796691, 0.09313004,
        0.06530779, 0.17998397, 0.10498536, 0.08969524, 0.09245632]],
      dtype=float32)

La perte `losses.SparseCategoricalCrossentropy` prend un vecteur de logits et un indice `True` et renvoie une perte scalaire pour chaque exemple.

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

Cette perte est égale au log de probabilité négatif de la vraie classe : elle est nulle si le modèle est sûr de la bonne classe.

Ce modèle non entraîné donne des probabilités proches du hasard (1/10 pour chaque classe), donc la perte initiale devrait être proche de `-tf.math.log(1/10) ~= 2.3`.

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.7286441

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

La méthode `Model.fit` ajuste les paramètres du modèle pour minimiser la perte :

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
1875/1875 [==============================] - 1s 362us/step - loss: 0.5016 - accuracy: 0.8523

La méthode `Model.evaluate` vérifie les performances des modèles, généralement sur un "[Validation-set](https://developers.google.com/machine-learning/glossary#validation-set)" ou "[Test-set](https://developers.google.com/machine-learning/glossary#test-set)".

In [11]:
model.evaluate(x_test,  y_test, verbose=2)

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
313/313 - 0s - loss: 0.0935 - accuracy: 0.9731


[0.09348230808973312, 0.9731000065803528]

Le classificateur d'images est maintenant entraîné à une précision d'environ 98 % sur cet ensemble de données. Pour en savoir plus, lisez les [TensorFlow tutorials](https://www.tensorflow.org/tutorials/).

Si vous souhaitez que votre modèle renvoie une probabilité, vous pouvez envelopper le modèle entraîné et lui attacher le softmax :

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.72369241e-09, 1.70626723e-13, 2.67196265e-06, 1.14372575e-04,
        3.78817745e-13, 2.28373494e-07, 1.81679336e-17, 9.99879479e-01,
        4.48904586e-07, 2.73176011e-06],
       [3.07573735e-08, 3.21239000e-04, 9.95400846e-01, 4.27489448e-03,
        2.41182240e-19, 4.83871077e-07, 9.80935653e-08, 8.64787571e-13,
        2.53265716e-06, 1.14139754e-16],
       [2.65035254e-07, 9.98849630e-01, 6.32762676e-05, 1.26328732e-05,
        5.96433165e-06, 6.94740811e-06, 4.31246872e-06, 9.94553207e-04,
        6.24215754e-05, 8.78397088e-08],
       [9.99999523e-01, 1.53276371e-18, 3.23648834e-07, 2.58971600e-09,
        2.59920693e-13, 8.58066951e-09, 9.32436564e-08, 2.97899607e-08,
        2.75593125e-11, 2.78946821e-09],
       [1.01417887e-08, 2.94391976e-15, 3.76814427e-07, 1.65012781e-10,
        9.98044491e-01, 2.16606000e-09, 2.03489581e-08, 2.87359603e-06,
        5.30654383e-08, 1.95231673e-03]], dtype=float32)>